## EX 3.- PDP to explain the price of a house.
### EXERCISE:
Apply the previous concepts to predict the price of a house from the database kc_house_data.csv. In this case, use again a random forest approximation for the prediction based on the features bedrooms, bathrooms, sqft_living, sqft_lot, floors and yr_built. 
Use the partial dependence plot to visualize the relationships the model learned.

BE CAREFUL: due to the size, extract a set of random samples from the BBDD before generating the data for the Partial Dependency Plot. 

We have to follow the same process as we did in exercise number 1, with the only difference that here we should select some of the features and not all; and we need to made a sample of 500 observations.
```{r, warning=FALSE}
library(randomForest) 
library(plyr) 
library(dplyr)
library(caret)

house <- read.csv("kc_house_data.csv")

set.seed(123)
df_sample <- house[sample(1:nrow(house), 500), ]

#Seleccionar las columnas relevantes para el modelo
X <- df_sample[, c("bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "yr_built")]
y <- df_sample$price

#Crear una partición de los datos en train y test
#80% de datos para entrenamiento y 20% para test
set.seed(123)
indices <- sample(2, nrow(X), replace = TRUE, prob = c(0.8, 0.2))
trainX <- X[indices == 1, ]
trainY <- y[indices == 1]
testX <- X[indices == 2, ]
testY <- y[indices == 2]