## EX 2.- Bidimensional Partial Dependency Plot.
### EXERCISE:
Generate a 2D Partial Dependency Plot with humidity and temperature to predict the number of bikes rented depending on those parameters.

BE CAREFUL: due to the size, extract a set of random samples from the BBDD before generating the data for the Partial Dependency Plot. 

Show the density distribution of both input features with the 2D plot as shown in the class slides. 

TIP: Use geom_tile() to generate the 2D plot. Set width and height to avoid holes. 

### QUESTION:
Interpret the results.

```{r, warning=FALSE}
library(dplyr)
#Extract random samples 
muestras <- sample_n(bike_rental, size = 250)

ggplot(muestras, aes(x=hum, y=temp)) +
  geom_tile(width = 0.3, height = 0.3)

#We show the relationships between these features and cnt in the next code 
ggplot(muestras, aes(x=hum, y=temp)) +
  geom_point(aes(colour=cnt)) +
  geom_tile(width = 0.3, height = 0.3)

```

The interpretation in this case is quite simple: the Y-axis corresponds to the temperature values, while the X-axis corresponds to the humidity values. In addition, on the right we see a legend with a colour scale from highest to lowest bicycle rental. 

It is enough to choose a point on the graph and see the colour of the one we have. If it is lighter, it means that in those conditions of temperature and humidity there is a greater number of rentals. Logically, the lower the humidity and the higher the temperature, the more bicycle rentals are produced.